# Generated by Django 4.2 on 2023-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
