# Generated by Django 4.2 on 2023-04-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
