# Generated by Django 4.2 on 2023-04-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
    ]
