# Generated by Django 4.2 on 2023-04-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_orders_first_name_orders_last_name_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='house_number',
            field=models.CharField(max_length=300),
        ),
    ]
